### ISSUE TITLE
Thank You for This Amazing Node

### ISSUE THREAD

**Issue by santhosh-factoryiq** [colinl/node-red-guaranteed-delivery#6]
I just wanted to thank you for creating this node. It's incredibly well-made and has been a game-changer for ensuring guaranteed delivery across the network. I am testing it all and I am sure it works so well. amazing work! 🙌

**Comment by colinl** [comment]
Thanks that is great to know. Out of interest, what is the application, if you are able to tell me?
Could you give it a rating on its node-red page please if you have not already done so? https://flows.nodered.org/node/@colinl/node-red-guaranteed-delivery

You can buy me a coffee if you are ever in West Wales, UK.

**Comment by santhosh-factoryiq** [comment]
We're a new startup in India, testing out this node to reliably queue data from PLCs to our MQTT server at the gateway. 

Unfortunately, I can’t buy you a coffee right now, but I’d love to when I visit West Wales in the future. Thanks again for your contributions to the community!

Rated as well at node-red page...

**Comment by colinl** [comment]
Thanks
